apiVersion: v1
kind: Service
metadata:
  labels:
    service: persons-grpc
  name: persons-grpc
spec:
  ports:
  - name: "30005"
    port: 30005
    targetPort: 5005
  selector:
    service: persons-grpc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: persons-grpc
  name: persons-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: persons-grpc
  template:
    metadata:
      labels:
        service: persons-grpc
    spec:
      containers:
      - image: rodrigodalamangas/persons-grpc:latest
        name: persons-grpc
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
